apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: up7v5fqpl-python 
  janus-idp.io/tekton: up7v5fqpl-python
  backstage.io/kubernetes-id: up7v5fqpl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: up7v5fqpl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml