apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: up7v5fqpl-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:cf95e9ebf87eb8cb320168f86327322903e574e6@sha256:c6bee2f68df14063d36e255c1a28af995e54e92808234e64acbc00ef2e3ea104
          name: container-image
